[project]
name = "pyplot-prettify"
version = "0.1.0"
authors = [
  {name = "Aran Garrod", email = "aran.garrod@gmail.com"},
]
description = "Some simple pyplot-based plotting helper functions to clean up plots."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "pre-commit>=4.5.1",
]
